name: Deploy DashHA to Mikr.us

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Deploy via SSH
        run: |
          sshpass -p "${{ secrets.DEV_VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_VPS_USER }}@${{ secrets.DEV_VPS_HOST }} << 'EOF'
            echo ">>> Wchodzę do repo i pulluję najnowszy kod"
            cd /var/www/git/DashHA
            git pull origin develop

            echo ">>> Czyścić katalog publikacji"
            sudo rm -rf /var/www/publish/DashHA/*

            echo ">>> Publikuję aplikację do katalogu produkcyjnego"
            dotnet publish /var/www/git/DashHA/DashHA/DashHA/DashHA.csproj -c Release -o /var/www/publish/DashHA
          
            echo ">>> Restartuję usługę systemd"
            sudo systemctl restart dashha

            echo ">>> Status usługi:"
            sudo systemctl status dashha --no-pager
          EOF