name: Deploy DashHA to Mikr.us

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Deploy via SSH
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'

            echo ">>> Wchodzę do repo i pulluję najnowszy kod"

		if [ ! -d "/var/www/git/DashHA/.git" ]; then
  			echo ">>> Repozytorium nie istnieje – klonuję"
  			git clone https://github.com/sftw01/DashHA.git /var/www/git/DashHA
		else
  			echo ">>> Repozytorium istnieje – wykonuję git pull"
  			cd /var/www/git/DashHA
  			git pull origin master
		fi

            echo ">>> Publikuję aplikację do katalogu produkcyjnego"
            dotnet publish DashHA/DashHA.csproj -c Release -o /var/www/publish/DashHA

            echo ">>> Restartuję usługę systemd"
            sudo systemctl restart dashha

            echo ">>> Status usługi:"
            sudo systemctl status dashha --no-pager
          EOF